---
title: "Interview Analysis"
author: "Olivia Imner"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
#PACKAGES
packages <- c(
  "printr",
  "ggthemes",
  "tidyverse",
  "readxl"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

```{r}
#read data
data <- read_excel(path = "~/Github/thesis_document/interview/interviewScores.xlsx") %>%
  mutate(Nr = parse_factor(Nr, levels = unique(Nr))) %>%
  mutate(Section = if_else(
      Section == "Användarbarhet och feedback på prestation", 
      "Användarbarhet och feedback\npå prestation", Section
    )) %>%
  mutate(Section = parse_factor(Section, levels = unique(Section))) %>%
  mutate(Modell = case_when(
    Modell == "AT" ~ "ATM",
    Modell == "DI" ~ "DIM", 
    Modell == "KL" ~ "KLM"
  ))
```

```{r, fig.align="center", fig.width=8, fig.height=6, message = FALSE}
figure1a <- data %>%
  ggplot() +
  geom_bar(aes(Nr, Poäng, fill = Modell), stat = "identity") +
  facet_wrap(~Section, scales = "free_x") +
  theme_bw() +
  scale_fill_ptol() +
  labs(x = "Frågans identifieringsnummer") +
  theme(legend.position = "top")

figure1a
# ggsave(
#   plot = figure1a,
#   filename = 'figure1a.pdf',
#   device = cairo_pdf,
#   height = 60,
#   width = 93,
#   units = "mm"
# )
```

```{r}
data %>% 
  group_by(Modell) %>% 
  summarize(
    `Sum of Points` = sum(Poäng),
    `Median Points` = median(Poäng),
    `Mean Points` = mean(Poäng)
  )
```

```{r, fig.align="center", fig.width=8, fig.height=6, message = FALSE}
figure1b <- data %>%
  ggplot() +
  geom_dotplot(
    aes(Modell, Poäng, fill = Modell), 
    binaxis = "y", stackdir = "center", binwidth = 0.1
  ) +
  geom_point(
    data = . %>% 
    group_by(Modell) %>% 
    summarize(`Mean Points` = mean(Poäng)),
    aes(Modell, `Mean Points`), shape = 95, size = 10,
    colour = "grey30"
  ) +
  geom_linerange(
    data = . %>%
      group_by(Modell) %>%
      summarize(
        sd.h = mean(Poäng) + sd(Poäng), 
        sd.l = mean(Poäng) - sd(Poäng)
      ),
    aes(Modell, ymin = sd.l, ymax = sd.h),
    colour = "grey30"
  ) +
  theme_bw() +
  theme(legend.position = "top") +
  scale_fill_ptol() +
  scale_colour_ptol() +
  guides(fill = FALSE)

figure1b
# ggsave(
#   plot = figure1b,
#   filename = 'figure1b.pdf',
#   device = cairo_pdf,
#   height = 60,
#   width = 93,
#   units = "mm"
# )
```

