---
title: "Evaluation Analysis"
author: "Olivia Imner"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r, message = FALSE}
#PACKAGES
packages <- c(
  "printr",
  "ggthemes",
  "tidyverse",
  "readxl"
)
purrr::walk(packages, library, character.only = TRUE)
rm(packages)
```

```{r}
#read data
data <- read_excel(path = "~/Github/thesis_document/evaluation/evaluationResultsOfficial.xlsx")
```

### Score as a function of Phase

```{r, fig.align="center", fig.width=8, fig.height=6, message = FALSE}
figure2a <- data %>% 
  mutate(Phase = case_when(
    Phase == "Bedömning och utvärderings fas" ~ "Bedömning och\nutvärdering",
    Phase == "Övervakning och återkoppling fas" ~ "Övervakning och\nåterkoppling",
    Phase == "Praktik fas" ~ "Praktik",
    Phase == "Presentation fas" ~ "Presentation",
    TRUE ~ "error"
  )) %>%
  mutate(Phase = parse_factor(Phase, levels = c(
    "Presentation", "Praktik", 
    "Bedömning och\nutvärdering", "Övervakning och\nåterkoppling"
  ))) %>%
  ggplot() +
  geom_dotplot(
    aes(Phase, `Score (0-5)`),
    binwidth = 1, binaxis = "y", binpositions = "bygroup", stackdir = "center", 
    position = position_dodge(), dotsize = 0.1, alpha = 0.75
  ) +
  geom_point(
    data = . %>%
      group_by(Phase) %>%
      summarize(mean = mean(`Score (0-5)`)),
    aes(Phase, mean), shape = 95, size = 10, colour = "grey30"
  ) +
  geom_linerange(
    data = . %>%
      group_by(Phase) %>%
      summarize(
        sd.l = mean(`Score (0-5)`) - sd(`Score (0-5)`),
        sd.h = mean(`Score (0-5)`) + sd(`Score (0-5)`)
      ),
    aes(Phase, ymin = sd.l, ymax = sd.h), colour = "grey30"
  ) +
  scale_y_continuous(breaks = seq(0, 6, 1)) +
  labs(x = "Fas", y = "Poäng (0-5)") +
  theme_bw() +
  theme(
    plot.title = element_blank(),
    plot.margin = unit(rep(0.1, 4), "lines"),
    legend.position = "top",
    legend.background = element_blank(),
    legend.box.spacing = unit(5, "pt"), 
    legend.margin = margin(rep(0, 4), unit = "pt"),
    legend.key.size = unit(1/5, "cm"),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    axis.title = element_text(size = 14),
    axis.title.x = element_text(margin = margin(t = 5)),
    axis.text = element_text(size = 12),
    axis.ticks = element_line(size = 0.25),
    axis.ticks.length = unit(1/15, "cm"),
    strip.text.x = element_text(
      size = 12,
      margin = margin(7, 0, 7, 0, "pt")
    ),
    panel.border = element_rect(fill = NA, size = 0.15)
  ) +
  guides(fill = guide_legend(override.aes = list(size = 5)))

figure2a

ggsave(
  plot = figure2a,
  filename = 'figure2a.pdf',
  device = cairo_pdf,
  height = 170,
  width = 150,
  units = "mm"
)
```

### Score as a function of Phase and Element

```{r, fig.align="center", fig.width=8, fig.height=6, message = FALSE}
figure2b <- data %>%
  mutate(Element = case_when(
    Element == "Erfarenheter och färdigheter" ~ "Erfarenheter / färdigheter",
    Element == "Inlärning av specifik kunskap eller färdighet" ~ "Inlärning av kunskap (ISKF)",
    Element == "Beskrivningar och scenario" ~ "Beskrivningar / scenario",
    Element == "Förklaring till vad som ska läras" ~ "Inlärnings förklaringar (FTL)",
    Element == "Förståelse" ~ "Förståelse",
    Element == "Guidning" ~ "Guidning",
    Element == "Självständiga övningar" ~ "Självständiga övningar",
    Element == "Periodisk granskning" ~ "Periodisk granskning",
    Element == "Validering" ~ "Validering",
    Element == "Sammanfattning" ~ "Sammanfattning",
    Element == "Ledtrådar och uppmaningar" ~ "Ledtrådar / uppmaningar",
    Element == "Support" ~ "Support"
  )) %>%
  mutate(Element = parse_factor(Element, levels = unique(Element))) %>%
  mutate(Phase = str_replace(Phase, "(.*).{4}$", "\\1")) %>%
  mutate(Phase = case_when(
    Phase == "Bedömning och utvärderings" ~ "Bedömning och\nutvärdering",
    Phase == "Övervakning och återkoppling" ~ "Övervakning och\nåterkoppling",
    TRUE ~ Phase
  )) %>%
  mutate(Phase = parse_factor(
    Phase, 
    levels = c(
      "Presentation", "Praktik", "Övervakning och\nåterkoppling", 
      "Bedömning och\nutvärdering"
    )
  )) %>%
  ggplot() +
  geom_dotplot(
    aes(Element, `Score (0-5)`, fill = Phase),
    binwidth = 0.1, binaxis = "y", binpositions = "bygroup", stackdir = "center", 
    position = position_dodge(), dotsize = 1.5
  ) +
  geom_point(
    data = . %>%
      group_by(Element) %>%
      summarize(mean = mean(`Score (0-5)`)),
    aes(Element, mean), shape = 95, size = 10, colour = "grey30"
  ) +
  geom_linerange(
    data = . %>%
      group_by(Element) %>%
      summarize(
        sd.l = mean(`Score (0-5)`) - sd(`Score (0-5)`),
        sd.h = mean(`Score (0-5)`) + sd(`Score (0-5)`)
      ),
    aes(Element, ymin = sd.l, ymax = sd.h), colour = "grey30"
  ) +
  scale_y_continuous(breaks = seq(0, 5, 1)) +
  labs(y = "Poäng (0-5)") +
  theme_bw() +
  theme(
    plot.title = element_blank(),
    plot.margin = unit(rep(0.1, 4), "lines"),
    legend.position = "top",
    legend.background = element_blank(),
    legend.box.spacing = unit(5, "pt"), 
    legend.margin = margin(rep(0, 4), unit = "pt"),
    legend.key.size = unit(1/5, "cm"),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.text.align = 0.5,
    axis.title = element_text(size = 14),
    axis.title.x = element_text(margin = margin(t = 5)),
    axis.text = element_text(size = 12),
    axis.text.x = element_text(angle = 90, hjust = 0.5),
    axis.ticks = element_line(size = 0.25),
    axis.ticks.length = unit(1/15, "cm"),
    strip.text.x = element_text(
      size = 12,
      margin = margin(7, 0, 7, 0, "pt")
    ),
    panel.border = element_rect(fill = NA, size = 0.15)
  ) +
  guides(fill = guide_legend(title = "Fas", override.aes = list(size = 5)))

figure2b

ggsave(
  plot = figure2b,
  filename = 'figure2b.pdf',
  device = cairo_pdf,
  height = 170,
  width = 150,
  units = "mm"
)
```

### Score as a function of Course

```{r, fig.align="center", fig.width=8, fig.height=6, message = FALSE}
figure3a <- data %>% 
  ggplot() +
  geom_dotplot(
    aes(Course, `Score (0-5)`),
    binwidth = 1, binaxis = "y", binpositions = "bygroup", stackdir = "center", 
    position = position_dodge(), dotsize = 0.1, alpha = 0.75
  ) +
  geom_point(
    data = . %>%
      group_by(Course) %>%
      summarize(mean = mean(`Score (0-5)`)),
    aes(Course, mean), shape = 95, size = 10, colour = "grey30"
  ) +
  geom_linerange(
    data = . %>%
      group_by(Course) %>%
      summarize(
        sd.l = mean(`Score (0-5)`) - sd(`Score (0-5)`),
        sd.h = mean(`Score (0-5)`) + sd(`Score (0-5)`)
      ),
    aes(Course, ymin = sd.l, ymax = sd.h), colour = "grey30"
  ) +
  scale_y_continuous(breaks = seq(0, 6, 1)) +
  labs(x = "Kurs", y = "Poäng (0-5)") +
  theme_bw() +
  theme(
    plot.title = element_blank(),
    plot.margin = unit(rep(0.1, 4), "lines"),
    legend.position = "top",
    legend.background = element_blank(),
    legend.box.spacing = unit(5, "pt"), 
    legend.margin = margin(rep(0, 4), unit = "pt"),
    legend.key.size = unit(1/5, "cm"),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.text.align = 0.5,
    axis.title = element_text(size = 14),
    axis.title.x = element_text(margin = margin(t = 5)),
    axis.text = element_text(size = 12),
    axis.ticks = element_line(size = 0.25),
    axis.ticks.length = unit(1/15, "cm"),
    strip.text.x = element_text(
      size = 12,
      margin = margin(7, 0, 7, 0, "pt")
    ),
    panel.border = element_rect(fill = NA, size = 0.15)
  ) +
  guides(fill = guide_legend(title = "Fas", override.aes = list(size = 5)))

figure3a

ggsave(
  plot = figure3a,
  filename = 'figure3a.pdf',
  device = cairo_pdf,
  height = 170,
  width = 150,
  units = "mm"
)
```

### Score as a function of Phase and Course

```{r, fig.align="center", fig.width=8, fig.height=6, message = FALSE}
figure3b <- data %>% 
  mutate(Phase = str_replace(Phase, "(.*).{4}$", "\\1")) %>%
  mutate(Phase = if_else(Phase == "Bedömning och utvärderings", "Bedömning och utvärdering", Phase)) %>%
  mutate(Phase = parse_factor(
    Phase, 
    levels = c(
      "Presentation", "Praktik", "Övervakning och återkoppling", 
      "Bedömning och utvärdering"
    )
  )) %>%
  ggplot() +
  geom_dotplot(
    aes(Course, `Score (0-5)`, fill = Course, group = interaction(Course, Phase)),
    binwidth = 1, binaxis = "y", binpositions = "bygroup", stackdir = "center", 
    position = position_dodge(), dotsize = 0.3
  ) +
  geom_point(
    data = . %>%
      group_by(Course, Phase) %>%
      summarize(mean = mean(`Score (0-5)`)),
    aes(Course, mean), shape = 95, size = 10, colour = "grey30"
  ) +
  geom_linerange(
    data = . %>%
      group_by(Course, Phase) %>%
      summarize(
        sd.l = mean(`Score (0-5)`) - sd(`Score (0-5)`),
        sd.h = mean(`Score (0-5)`) + sd(`Score (0-5)`)
      ),
    aes(Course, ymin = sd.l, ymax = sd.h), colour = "grey30"
  ) +
  facet_wrap(~Phase) +
  scale_y_continuous(breaks = seq(0, 6, 1)) +
  labs(x = "Kurs", y = "Poäng (0-5)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90), legend.position = "top") +
  theme(
    plot.title = element_blank(),
    plot.margin = unit(rep(0.1, 4), "lines"),
    legend.position = "top",
    legend.background = element_blank(),
    legend.box.spacing = unit(5, "pt"), 
    legend.margin = margin(rep(0, 4), unit = "pt"),
    legend.key.size = unit(1/5, "cm"),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.text.align = 0.5,
    axis.title = element_text(size = 14),
    axis.title.x = element_text(margin = margin(t = 5)),
    axis.text = element_text(size = 12),
    axis.ticks = element_line(size = 0.25),
    axis.ticks.length = unit(1/15, "cm"),
    strip.text.x = element_text(
      size = 12,
      margin = margin(7, 0, 7, 0, "pt")
    ),
    panel.border = element_rect(fill = NA, size = 0.15)
  ) +
  guides(fill = FALSE)

figure3b

ggsave(
  plot = figure3b,
  filename = 'figure3b.pdf',
  device = cairo_pdf,
  height = 170,
  width = 150,
  units = "mm"
)
```
